apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      volumes:
      - name: config
        configMap: 
          name: terminus-config
          optional: true
      - name: cgroupfs
        hostPath:
          path: /sys/fs/cgroup 
      containers:
      - command:
        - /manager
        image: controller:latest
        name: manager
        securityContext:
          privileged: true
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: config 
          mountPath: /etc/terminus
        - name: cgroupfs
          mountPath: /sys/fs/cgroup 
        # This never changes. The code assumes the socket is mounted here.
        - name: containerd-sock 
          mountPath: /run/containerd/containerd.sock
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
