# permissions to do edit podlimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podlimit-editor-role
rules:
- apiGroups:
  - boundry.terminus
  resources:
  - podlimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boundry.terminus
  resources:
  - podlimits/status
  verbs:
  - get
  - patch
  - update
